:update: forgot then

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -33,7 +33,9 @@ jobs:
           for i in ${{ env.EXECUTABLES }}
           do
             if [ ! -x "$i"]
-              exit 1
+              then
+                echo "Error: $executable not found or not executable"
+                exit 1
             fi
           done
 
